services:
  db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    build: ./desafio_hyperativa
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./desafio_hyperativa:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always

  celery:
    build: ./desafio_hyperativa
    command: celery -A desafio_hyperativa worker --loglevel=info
    volumes:
      - ./desafio_hyperativa:/code
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data:
