# Generated by Django 3.2.25 on 2024-07-29 05:52

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=29)),
                ('_card_number_data', encrypted_fields.fields.EncryptedCharField(editable=False, max_length=255)),
                ('card_number', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_card_number_data', hash_key='cc8e86eeadf45401460a655ac01ad5651960322e11d43ecf6229b8e2dbe69208', max_length=66, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardsBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
