# Generated by Django 3.2.25 on 2024-07-29 18:56

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsbatch',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[cards.validators.validate_file_extension]),
        ),
    ]
