# Generated by Django 3.2.25 on 2024-07-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_cardsbatch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=255),
        ),
    ]
